Test
Mte90/Contribute-to-opensource-the-right-way pull request #31
Opened 2023-12-14 21:08 UTC by 22dt91

I've created a new branch from scratch, now without trimming lines.
It contains my review for chap1->6

2023-12-15 10:35 UTC, Mte90 commented
Thanks a lot!
I will wait before to merge (and to review all the changes), I will need also your name to add in the thanks list at the end of the book :-)

I still don't know when I will do the 4th edition but maybe I can do just a minor release with those fix.

2023-12-15 22:34 UTC, 22dt91 commented
I've reviewed also the last chapters, I'm waiting for the new version (when you have time to review the PR).
Btw, I'm Denny Tremolada

2023-12-27 11:19 UTC, Mte90 requested changes
If you revert/put that file back I can merge your contribution :-)

2023-12-27 11:19 UTC, Mte90 commented on manuscript/Book.txt
Can you revert this change and reput that file as it is needed to generated the pdf and the other versions?

2023-12-27 13:17 UTC, 22dt91 commented on manuscript/Book.txt
Done!

2023-12-27 14:59 UTC, merged

2023-12-27 14:59 UTC, Mte90 commented
Probably I will do a new release after the fosdem next february with all your fixes1
Thanks!

2025-06-22 19:13 UTC, DeinAlptraum commented on manuscript/appendix-3.md
> +There is a this huge misconception that, because it’s free, it’s for everyone. Excluding the fact that open source doesn’t mean that it’s free, this is basically wrong.
Adding the `a` here is wrong, the sentence was correct before without it.

2025-06-22 19:13 UTC, DeinAlptraum commented on manuscript/appendix-3.md
> +A pragmatic analysis I get from the role mentor came from the article [Why we stopped making Einsteins](https://erikhoel.substack.com/p/why-we-stopped-making-einsteins?s=r), where the reason basicall
`let` was correct here because we are talking about the mentor's past experiences.

2025-06-22 19:13 UTC, DeinAlptraum commented on manuscript/preface.md
> +One real example from the [Linux Kernel, a message by Qu Wenruo, with relative HackerNews discussion](https://news.ycombinator.com/item?id=27629366) shows us sometimes contributions are just a number
`maintainerz` is not a word, this should be `maintainers`

2025-06-22 19:13 UTC, DeinAlptraum commented on manuscript/conclusion.md
> +So IT departments prefer Office 365 because they don’t need to take care of supporting it, installing it and so on (welcome to the cloud baby) but this opens the door to other questions. Where are th
`theme` is not a word, should be `there`

2025-06-22 19:13 UTC, DeinAlptraum commented on manuscript/conclusion.md
> +The [Open Source Contributor Index](https://opensourceindex.io/) it is a practical way to see the biggest company contributors to the ecosystem, that are leaded by Google, Microsoft and Red Hat.
This changes the meaning of the sentence.

2025-06-22 19:13 UTC, DeinAlptraum commented on manuscript/chapter4-gotta-catch-em-all.md
> +* Talk about how much fun and interesting is growing skills
This was more correct with the `it` there